### PR TITLE
Switch IMASDD to IMAS and make adaptations

### PR DESCRIPTION
**Pull request by eldond**
This PR should be squashed.

Switch IMASDD to IMAS

- Replace all IMASDD references with IMAS
- Add flux map grid type info so IMAS expressions can work
- Adjust keywords in imas2json to make it not take forever

### CODE REVIEW

**Comment by eldond** [comment]
@anchal-physics it's failing because it can't clone IMAS; I think that's okay because we expect IMAS to go public later.

**Comment by anchal-physics** [comment]
I can't test this branch locally either as IMAS has not been shared with me yet. It would be better to wait for IMAS to go public before merging this with our master branch. Meanwhile, if you need IMAS features for some other development you can rebase from this imas branch.

**Comment by eldond** [comment]
@orso82 did you intend to share IMAS with Anchal?

**Comment by orso82** [comment]
yes, @anchal-physics should have access

**Comment by anchal-physics** [comment]
One test failed on set tolerance on my computer:
```bash
% julia --project test/runtests.jl --geqdsk_to_imas
/Users/gupta/Git/ProjectTorreyPines/SD4SOLPS/src/../sample/g184833.03600
 --- 
(65, 65)(65, 65)
/Users/gupta/Git/ProjectTorreyPines/SD4SOLPS/src/../sample/geqdsk_iter_small_sample
 --- 
(65, 65)(65, 65)
geqdsk_to_imas: Test Failed at /Users/gupta/Git/ProjectTorreyPines/SD4SOLPS/test/runtests.jl:404
  Expression: maximum(psin_bry) < 1.0 + tolerance
   Evaluated: 1.0023268315692309 < 1.002

Stacktrace:
 [1] macro expansion
   @ ~/.julia/juliaup/julia-1.10.4+0.aarch64.apple.darwin14/share/julia/stdlib/v1.10/Test/src/Test.jl:672 [inlined]
 [2] macro expansion
   @ ~/Git/ProjectTorreyPines/SD4SOLPS/test/runtests.jl:404 [inlined]
 [3] macro expansion
   @ ~/.julia/juliaup/julia-1.10.4+0.aarch64.apple.darwin14/share/julia/stdlib/v1.10/Test/src/Test.jl:1577 [inlined]
 [4] top-level scope
   @ ~/Git/ProjectTorreyPines/SD4SOLPS/test/runtests.jl:330
/Users/gupta/Git/ProjectTorreyPines/SD4SOLPS/test/../sample/ITER_Lore_2296_00000/EQDSK/g002296.00200
 --- 
(257, 513)(257, 513)
Test Summary:  | Pass  Fail  Total  Time
geqdsk_to_imas |   74     1     75  7.2s
ERROR: LoadError: Some tests did not pass: 74 passed, 1 failed, 0 errored, 0 broken.
in expression starting at /Users/gupta/Git/ProjectTorreyPines/SD4SOLPS/test/runtests.jl:328
```

**Comment by eldond** [comment]
This could be because I tried to adjust the boundary flux. The sample is very low res and the psin=1 contour was showing up as an open field line outboard of the X-point, which broke some IMAS calculations. So I made an option to correct it until the contour line would close. I should've just upsampled the EFIT mesh, I guess. I'll turn that option off by default.

**Comment by anchal-physics** [comment]
All dependencies are now public for this branch, so the CI tests should pass if everything is ok. Currently, 6 tests are failing in geqdsk_to_imas:
https://github.com/ProjectTorreyPines/SD4SOLPS.jl/actions/runs/10223457708/job/28289787457?pr=78#step:10:889

**Review by anchal-physics — APPROVED** [review]
Most changes are sed for IMASDD to IMAS

New feature includes boundary flux correction using IMAS.flux_surface().

**Pull request merged**
